import fs from "node:fs";
import path from "node:path";
import { environmentFailure } from "../cli/output.mjs";

const SOURCE_EXTENSIONS = new Set([
  ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs",
  ".py", ".java", ".kt", ".go", ".rs", ".rb", ".php",
  ".cs", ".swift", ".c", ".cc", ".cpp", ".h", ".hpp",
  ".sql", ".sh", ".zsh", ".bash",
]);
const CONFIG_EXTENSIONS = new Set([
  ".json", ".yml", ".yaml", ".toml", ".xml", ".ini", ".env", ".properties",
]);
const DOC_EXTENSIONS = new Set([".md", ".txt", ".rst"]);

function requireDir(dir, label) {
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) {
    throw environmentFailure(`${label} does not exist or is not a directory: ${dir}`);
  }
}

export function codebaseFileKind(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  const base = path.basename(filePath).toLowerCase();
  if (SOURCE_EXTENSIONS.has(ext)) return "source";
  if (CONFIG_EXTENSIONS.has(ext) || ["dockerfile", "makefile"].includes(base)) return "config";
  if (DOC_EXTENSIONS.has(ext)) return "doc";
  return "other";
}

export function scanCodebase(target, listFiles) {
  const files = listFiles(target)
    .map((filePath) => {
      const stat = fs.statSync(filePath);
      return {
        path: path.relative(target, filePath),
        ext: path.extname(filePath).toLowerCase() || path.basename(filePath).toLowerCase(),
        kind: codebaseFileKind(filePath),
        size: stat.size,
        modified: stat.mtime.toISOString(),
      };
    })
    .sort((a, b) => a.path.localeCompare(b.path));
  const sourceFiles = files.filter((file) => file.kind === "source");
  const testFiles = files.filter((file) => /(^|\/)(test|tests|spec|specs|__tests__)(\/|$)|(\.|-)(test|spec)\./i.test(file.path));
  const configFiles = files.filter((file) => file.kind === "config");
  const extensionCounts = new Map();
  const kindCounts = new Map();
  for (const file of files) {
    extensionCounts.set(file.ext, (extensionCounts.get(file.ext) || 0) + 1);
    kindCounts.set(file.kind, (kindCounts.get(file.kind) || 0) + 1);
  }
  const entryHints = files.filter((file) => /(^|\/)(main|index|app|server|cli|manage|package|pom|build|Cargo|go\.mod|pyproject|requirements|Dockerfile)/i.test(file.path));
  return { files, sourceFiles, testFiles, configFiles, extensionCounts, kindCounts, entryHints };
}

function formatCountMap(mapValue) {
  return [...mapValue.entries()]
    .sort((a, b) => String(a[0]).localeCompare(String(b[0])))
    .map(([key, count]) => `- \`${key}\`: ${count}`)
    .join("\n") || "- None";
}

function writeCodebaseScan(target, listFiles) {
  const scan = scanCodebase(target, listFiles);
  const codebaseDir = path.join(target, ".planning", "codebase");
  fs.mkdirSync(codebaseDir, { recursive: true });
  const generatedAt = new Date().toISOString();
  const statusPath = path.join(codebaseDir, "CODEBASE_STATUS.md");
  const structurePath = path.join(codebaseDir, "STRUCTURE.md");
  const testingPath = path.join(codebaseDir, "TESTING.md");
  const stackPath = path.join(codebaseDir, "STACK.md");
  const architecturePath = path.join(codebaseDir, "ARCHITECTURE.md");

  fs.writeFileSync(statusPath, `# Codebase Status\n\nGenerated: ${generatedAt}\n\n## Summary\n\n- Total files: ${scan.files.length}\n- Source files: ${scan.sourceFiles.length}\n- Test files: ${scan.testFiles.length}\n- Config files: ${scan.configFiles.length}\n\n## Kind Counts\n\n${formatCountMap(scan.kindCounts)}\n\n## Extension Counts\n\n${formatCountMap(scan.extensionCounts)}\n\n## Entry Hints\n\n${scan.entryHints.slice(0, 80).map((file) => `- \`${file.path}\` (${file.kind})`).join("\n") || "- None detected"}\n\n## Guard Notes\n\n- Existing projects should have non-zero source files before implementation workflows.\n- New projects may start with zero source files, but implementation and verification gates must be satisfied before completion.\n`);
  fs.writeFileSync(structurePath, `# Structure: ${path.basename(target)}\n\nGenerated by Zhulong Project Intelligence Kit on ${generatedAt}.\n\n## Source Files\n\n${scan.sourceFiles.slice(0, 200).map((file) => `- \`${file.path}\``).join("\n") || "- None found"}\n\n## Config Files\n\n${scan.configFiles.slice(0, 120).map((file) => `- \`${file.path}\``).join("\n") || "- None found"}\n\n## Other Files\n\n${scan.files.filter((file) => file.kind === "other").slice(0, 120).map((file) => `- \`${file.path}\``).join("\n") || "- None found"}\n`);
  fs.writeFileSync(testingPath, `# Testing\n\nGenerated: ${generatedAt}\n\n## Detected Test Files\n\n${scan.testFiles.slice(0, 120).map((file) => `- \`${file.path}\``).join("\n") || "- None detected"}\n\n## Next Pass\n\n- Confirm actual test commands in \`project.manifest.yml\` or package/build files.\n- Record required verification commands before completing guarded workflows.\n`);
  fs.writeFileSync(stackPath, `# Stack\n\nGenerated: ${generatedAt}\n\n## Detected Signals\n\n${scan.configFiles.slice(0, 120).map((file) => `- \`${file.path}\``).join("\n") || "- None detected"}\n\n## Extension Counts\n\n${formatCountMap(scan.extensionCounts)}\n`);
  fs.writeFileSync(architecturePath, `# Architecture\n\nGenerated: ${generatedAt}\n\n## Entry Hints\n\n${scan.entryHints.slice(0, 120).map((file) => `- \`${file.path}\``).join("\n") || "- None detected"}\n\n## Manual Follow-up\n\n- Identify subsystem boundaries.\n- Identify public APIs, jobs, screens, batch processes, and data stores.\n- Link Graphify/code-map evidence after \`zl-graph-build --run\`.\n`);
  return { scan, statusPath, structurePath, testingPath, stackPath, architecturePath };
}

export function createCodebaseCommand({ listFiles, formatGraphStatus, usage }) {
  return function codebase(args) {
    const subcommand = args._[0] || "scan";
    const target = path.resolve(args.target || process.cwd());
    requireDir(target, "Target");
    if (subcommand === "scan") {
      const result = writeCodebaseScan(target, listFiles);
      for (const filePath of [result.statusPath, result.structurePath, result.testingPath, result.stackPath, result.architecturePath]) {
        console.log(`write ${filePath}`);
      }
      console.log(`source files ${result.scan.sourceFiles.length}`);
      console.log(`test files ${result.scan.testFiles.length}`);
      return;
    }
    if (subcommand === "status") {
      const files = ["CODEBASE_STATUS.md", "STRUCTURE.md", "TESTING.md"];
      const states = files.map((name) => ({ name, exists: fs.existsSync(path.join(target, ".planning", "codebase", name)) }));
      for (const state of states) console.log(`${state.exists ? "ok" : "missing"} .planning/codebase/${state.name}`);
      console.log("\nGraph status:");
      console.log(formatGraphStatus(target));
      process.exitCode = states.every((state) => state.exists) ? 0 : 1;
      return;
    }
    usage();
    process.exitCode = 1;
  };
}
