export const WORKFLOW_COMMANDS = {
  "new-milestone": {
    publicCommand: "$zl-new-milestone",
    referenceCommand: "$gsd-new-milestone",
    workflowDoc: "core/workflows/new-milestone.md",
    packetKind: "milestone",
    handoffPrefix: "new-milestone",
    description: "Start a Zhulong milestone loop",
  },
  "spec-phase": {
    publicCommand: "$zl-spec-phase",
    referenceCommand: "$gsd-spec-phase",
    workflowDoc: "core/workflows/spec-phase.md",
    packetKind: "spec",
    handoffPrefix: "spec-phase",
    description: "Clarify requirements and specification evidence",
  },
  "discuss-phase": {
    publicCommand: "$zl-discuss-phase",
    referenceCommand: "$gsd-discuss-phase",
    workflowDoc: "core/workflows/discuss-phase.md",
    packetKind: "discuss",
    handoffPrefix: "discuss-phase",
    description: "Discuss decisions, unknowns, and implementation options",
  },
  "ui-phase": {
    publicCommand: "$zl-ui-phase",
    referenceCommand: "$gsd-ui-phase",
    workflowDoc: "core/workflows/ui-phase.md",
    packetKind: "ui",
    handoffPrefix: "ui-phase",
    description: "Design and validate UI implementation context",
  },
  debug: {
    publicCommand: "$zl-debug",
    referenceCommand: "$gsd-debug",
    workflowDoc: "core/workflows/debug.md",
    packetKind: "debug",
    handoffPrefix: "debug",
    description: "Systematic debugging",
  },
  "plan-phase": {
    publicCommand: "$zl-plan-phase",
    referenceCommand: "$gsd-plan-phase",
    workflowDoc: "core/workflows/plan-phase.md",
    packetKind: "plan",
    handoffPrefix: "plan-phase",
    description: "Phase planning",
  },
  "execute-phase": {
    publicCommand: "$zl-execute-phase",
    referenceCommand: "$gsd-execute-phase",
    workflowDoc: "core/workflows/execute-phase.md",
    packetKind: "execute",
    handoffPrefix: "execute-phase",
    description: "Phase execution",
  },
  "code-review": {
    publicCommand: "$zl-code-review",
    referenceCommand: "$gsd-code-review",
    workflowDoc: "core/workflows/code-review.md",
    packetKind: "review",
    handoffPrefix: "code-review",
    description: "Code review",
  },
  "verify-work": {
    publicCommand: "$zl-verify-work",
    referenceCommand: "$gsd-verify-work",
    workflowDoc: "core/workflows/verify-work.md",
    packetKind: "verify",
    handoffPrefix: "verify-work",
    description: "Work verification",
  },
  "complete-milestone": {
    publicCommand: "$zl-complete-milestone",
    referenceCommand: "$gsd-complete-milestone",
    workflowDoc: "core/workflows/complete-milestone.md",
    packetKind: "complete",
    handoffPrefix: "complete-milestone",
    description: "Complete and archive a milestone loop",
  },
};
