import fs from "node:fs";
import path from "node:path";
import { commandFailure, environmentFailure } from "../cli/output.mjs";

function requireDir(dir, label) {
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) {
    throw environmentFailure(`${label} does not exist or is not a directory: ${dir}`);
  }
}

function evidenceDir(target) {
  return path.join(target, ".planning", "evidence");
}

function evidenceTimestamp() {
  return new Date().toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z");
}

function splitOptionList(value) {
  if (!value) return [];
  return String(value).split(",").map((item) => item.trim()).filter(Boolean);
}

export function evidenceRecordFiles(target) {
  const dir = evidenceDir(target);
  if (!fs.existsSync(dir) || !fs.statSync(dir).isDirectory()) return [];
  return fs.readdirSync(dir)
    .filter((name) => name.endsWith(".md") && !["README.md", "INDEX.md", "RECORD_TEMPLATE.md"].includes(name))
    .map((name) => path.join(dir, name))
    .sort()
    .reverse();
}

function normalizeWritebackPath(target, value) {
  if (!value) return null;
  const raw = String(value).trim();
  const resolved = path.resolve(target, raw);
  const relative = path.relative(target, resolved);
  if (relative.startsWith("..") || path.isAbsolute(relative)) {
    throw commandFailure(`writeback target must be inside project: ${raw}`);
  }
  return resolved;
}

function uniqueList(items) {
  return [...new Set(items.filter(Boolean))];
}

function candidateRecordPaths(target, kind, value, slugify) {
  if (!value) return [];
  const raw = String(value).trim();
  if (!raw) return [];
  const baseDir = kind === "phase"
    ? path.join(target, ".planning", "phases")
    : kind === "debug"
      ? path.join(target, ".planning", "debug")
      : path.join(target, ".planning", "issues");
  const direct = normalizeWritebackPath(target, raw);
  const slug = slugify(raw, raw);
  const names = [raw, `${raw}.md`, `${slug}.md`, path.join(raw, "VALIDATION.md"), path.join(raw, "SUMMARY.md"), path.join(raw, "README.md")];
  return uniqueList([direct, ...names.map((name) => path.resolve(baseDir, name))]);
}

function resolveEvidenceWritebacks(target, args, slugify) {
  const values = [];
  const explicit = splitOptionList(args.writeback || args.writebacks);
  for (const item of explicit) values.push(normalizeWritebackPath(target, item));
  for (const kind of ["phase", "debug", "issue"]) {
    for (const item of candidateRecordPaths(target, kind, args[kind], slugify)) values.push(item);
  }
  const existing = uniqueList(values).filter((filePath) => fs.existsSync(filePath) && fs.statSync(filePath).isFile());
  return existing.length ? existing : explicit.map((item) => normalizeWritebackPath(target, item));
}

function appendEvidenceWriteback(target, recordPath, evidencePath, details) {
  const section = `\n\n## Zhulong Evidence Writeback - ${details.generatedAt}\n\n`
    + `- Evidence: \`${path.relative(target, evidencePath)}\`\n`
    + `- Summary: ${details.summary}\n`
    + `- Command: ${details.command || "Not recorded"}\n`
    + `- Result: ${details.result || "Not recorded"}\n`
    + `- Risk: ${details.risk || "Not recorded"}\n`
    + `- Rollback: ${details.rollback || "Not recorded"}\n`;
  fs.appendFileSync(recordPath, section);
}

function readEvidenceTitle(filePath) {
  const text = fs.readFileSync(filePath, "utf8");
  const title = text.split(/\r?\n/).find((line) => line.startsWith("# Evidence Record:"));
  return title ? title.replace("# Evidence Record:", "").trim() : path.basename(filePath, ".md");
}

function uniqueEvidencePath(dir, summary, slugify) {
  const base = `${evidenceTimestamp()}-${slugify(summary, "evidence")}`;
  let candidate = path.join(dir, `${base}.md`);
  let suffix = 2;
  while (fs.existsSync(candidate)) {
    candidate = path.join(dir, `${base}-${suffix}.md`);
    suffix += 1;
  }
  return candidate;
}

function writeEvidenceIndex(target, markdownCell) {
  const dir = evidenceDir(target);
  fs.mkdirSync(dir, { recursive: true });
  const records = evidenceRecordFiles(target);
  const generatedAt = new Date().toISOString();
  const rows = records.length
    ? records.map((filePath) => `| \`${path.basename(filePath)}\` | ${markdownCell(readEvidenceTitle(filePath))} |`).join("\n")
    : "| None | - |";
  const indexPath = path.join(dir, "INDEX.md");
  fs.writeFileSync(indexPath, `# Evidence Index: ${path.basename(target)}\n\nGenerated by Zhulong Project Intelligence Kit on ${generatedAt}.\n\n## Records\n\n| Record | Summary |\n| --- | --- |\n${rows}\n`);
  return { indexPath, records };
}

export function createEvidenceCommand({ formatGraphStatus, markdownCell, slugify, usage }) {
  function record(args) {
    const target = path.resolve(args.target || process.cwd());
    requireDir(target, "Target");
    const summary = args.summary || args.title || args._.slice(1).join(" ").trim() || "Manual evidence record";
    const generatedAt = new Date().toISOString();
    const dir = evidenceDir(target);
    fs.mkdirSync(dir, { recursive: true });
    const sources = splitOptionList(args.source || args.sources);
    const outPath = uniqueEvidencePath(dir, summary, slugify);
    const content = `# Evidence Record: ${summary}\n\nGenerated: ${generatedAt}\n\n## Scope\n\n- Phase: ${args.phase || "Not recorded"}\n- Issue/debug record: ${args.issue || args.debug || "Not recorded"}\n- Request: ${args.request || summary}\n\n## Specification Evidence\n\n${sources.length ? sources.map((source) => `- ${source}`).join("\n") : "- Not recorded"}\n\n## Code Map Evidence\n\n${formatGraphStatus(target)}\n\n## Verification\n\n- Command: ${args.recordCommand || "Not recorded"}\n- Result: ${args.result || args.status || "Not recorded"}\n\n## Remaining Risk\n\n${args.risk || "Not recorded"}\n\n## Rollback\n\n${args.rollback || "Not recorded"}\n\n## Follow-ups\n\n${args.followup ? `- [ ] ${args.followup}` : "- [ ] None recorded"}\n`;
    fs.writeFileSync(outPath, content);
    const index = writeEvidenceIndex(target, markdownCell);
    const writebacks = resolveEvidenceWritebacks(target, args, slugify);
    for (const recordPath of writebacks) {
      appendEvidenceWriteback(target, recordPath, outPath, {
        generatedAt,
        summary,
        command: args.recordCommand,
        result: args.result || args.status,
        risk: args.risk,
        rollback: args.rollback,
      });
    }
    console.log(`write ${outPath}`);
    console.log(`write ${index.indexPath}`);
    for (const recordPath of writebacks) console.log(`writeback ${recordPath}`);
  }

  function status(args) {
    const target = path.resolve(args.target || process.cwd());
    requireDir(target, "Target");
    const index = writeEvidenceIndex(target, markdownCell);
    console.log("Evidence status");
    console.log(`records ${index.records.length}`);
    if (index.records.length === 0) {
      console.log("Run: zl-evidence-record --target <repo> \"summary\" --command \"npm test\" --result \"passed\"");
      return;
    }
    for (const filePath of index.records.slice(0, 8)) console.log(`- ${path.basename(filePath)} ${readEvidenceTitle(filePath)}`);
  }

  return function evidence(args) {
    const subcommand = args._[0];
    if (subcommand === "record") return record(args);
    if (subcommand === "status") return status(args);
    usage();
    process.exitCode = 1;
  };
}
